# Generated by Django 5.2.2 on 2026-03-18 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songuser',
            unique_together={('song', 'user')},
        ),
    ]
